sudo: true
services:
  - docker
language: go
go:
  - 1.6
branches:
  only:
  - master
before_install:
  - openssl aes-256-cbc -K $encrypted_a9aeb6bf1959_key -iv $encrypted_a9aeb6bf1959_iv
  -in client-secret.json.enc -out client-secret.json -d
script:
  - make build
after_success: 
  - make deploy
notifications:
  slack: pachyderm:qmSCZSX1Q2yWxc6DjNZZFLGd
