sudo: false
deploy:
  provider: gae
  keyfile: client-secret.json
  project: pachyderm-sandbox
  skip_cleanup: true
  on: master
before_install:
  - openssl aes-256-cbc -K $encrypted_a9aeb6bf1959_key -iv $encrypted_a9aeb6bf1959_iv -in client-secret.json.enc -out client-secret.json -d
language: python
python: "2.7"
go: "1.6"
branches:
  only:
    - master
notifications:
  slack: pachyderm:qmSCZSX1Q2yWxc6DjNZZFLGd
script:
  - make build
  - echo "Travis - Done building"